//
//  Header.h
//  BAU7
//
//  Created by Dan Brooker on 9/26/21.
//

#ifndef Header_h
#define Header_h


#endif /* Header_h */
enum U7CharacterSprite
{
    HermitMaleCharacterSprite=154,
    WingedGargoyleCharacterSprite=226,
    HoodedRobedCharacterSprite=227,
    NudeManCharacterSprite=228,
    NudeWomanCharacterSprite=229,
    BohemothCharacterSprite=230,
    KnightCharacterSprite=247,
    FighterCharacterSprite=259,
    NobleMaleCharacterSprite=265,
    WingedGargoyleTwoCharacterSprite=274,
    FemaleGhostCharacterSprite=299,
    TradesmanCharacterSprite=304,
    MaleGhostCharacterSprite=317,
    HoodedRobedTwoCharacterSprite=318,
    PeasantMaleCharacterSprite=319,
    GhostCharacterSprite=337,
    LichKingCharacterSprite=354,
    UnicornCharacterSprite=375,
    CyclopsCharacterSprite=380,
    HydraCharacterSprite=381,
    PixieCharacterSprite=382,
    GuardCharacterSprite=394,
    PirateMaleCharacterSprite=401,
    BatlinCharacterSprite=403,
    HermitMaleTwoCharacterSprite=445,
    HermitFemaleCharacterSprite=446,
    HoodedRobedFemaleCharacterSprite=448,
    PeasantCrutchesCharacterSprite=449,
    PeasantLeglessCharacterSprite=450,
    NobleMaleTwoCharacterSprite=451,
    PeasantFemaleCharacterSprite=452,
    MerchantFemaleTwoCharacterSprite=454,
    MerchantMaleTwoCharacterSprite=455,
    NobleFemaleTwoCharacterSprite=456,
    PirateMaleTwoCharacterSprite=457,
    PirateMaleThreeCharacterSprite=458,
    PirateFemaleCharacterSprite=459,
    RangerMaleCharacterSprite=460,
    RangerFemaleCharacterSprite=461,
    FighterMaleCharacterSprite=462,
    FighterFemaleCharacterSprite=463,
    KnightMaleTwoCharacterSprite=464,
    IoloCharacterSprite=465,
    BrtishCharacterSprite=466,
    JesterCharacterSprite=467,
    MerchantMaleThreeCharacterSprite=468,
    PirateFemaleTwoCharacterSprite=469,
    PeasantChildCharacterSprite=471,
    NobleChildCharacterSprite=472,
    WingedGargoyleThreeCharacterSprite=473,
    WinglessGargoyleCharacterSprite=475,
    HorseCharacterSprite=476,
    FoxNecklaceCharacterSprite=477,
    MouseNecklaceCharacterSprite=478,
    EmpCharacterSprite=479,
    WingedGargoyleFourCharacterSprite=480,
    BatlinTwoCharacterSprite=482,
    DewRagMerchantCharacterSprite=485,
    ShaminoCharacterSprite=487,
    FighterMaleTwoCharacterSprite=488,
    SpikeCharacterSprite=489,
    FemaleRobedCharacterSprite=490,
    SlugCharacterSprite=491,
    CrocCharacterSprite=492,
    BatCharacterSprite=493,
    BeeCharacterSprite=494,
    CatCharacterSprite=495,
    DogCharacterSprite=496,
    ChickenCharacterSprite=498,
    RoperCharacterSprite=499,
    CowCharacterSprite=500,
    CyclopsTwoCharacterSprite=501,
    DeerCharacterSprite=502,
    RedDragoCharacterSprite=504,
    GreenDrakeCharacterSprite=505,
    HookCharacterSprite=506,
    FoxCharacterSprite=510,
    PhaserCharacterSprite=511,
    GremlinCharacterSprite=513,
    HeadlessCharacterSprite=514,
    GnatCharacterSprite=517,
    SkeletonMageCharacterSprite=519,
    MouseCharacterSprite=521,
    RatCharacterSprite=523,
    ReaperCharacterSprite=524,
    NessieCharacterSprite=525,
    SkeletonCharacterSprite=528,
    SnakeCharacterSprite=530,
    HarpyCharacterSprite=532,
    TrollCharacterSprite=533,
    WispCharacterSprite=534,
    SeaTentacleCharacterSprite=536,
    WolfCharacterSprite=537,
    FlyingMonkeyCharacterSprite=661,
    ScorpionCharacterSprite=706,
    DoveCharacterSprite=716,
    GuardMaleCharacterSprite=720,
    AvatarMaleCharacterSprite=721,
    HorseTwoCharacterSprite=727,
    StoneHarpyCharacterSprite=753,
    WinglessGargoyleTwoCharacterSprite=805,
    GuardFemaleCharacterSprite=806,
    TrollTwoCharacterSprite=861,
    ToddlerCharacterSprite=864,
    SpiderCharacterSprite=865,
    NobleFemaleCharacterSprite=881,
    NobleMaleThreeCharacterSprite=882,
    WinglessGargoyleThreeCharacterSprite=883,
    MerchantMaleCharacterSprite=884,
    BarkeepFemaleCharacterSprite=884,
    GuardFemaleTwoCharacterSprite=946,
    HoodedSkeletonMageCharacterSprite=952,
    MerchantMaleFourCharacterSprite=957,
    PeasantChildTwoCharacterSprite=965,
    SheepCharacterSprite=970,
    AvatarFemaleCharacterSprite=989,
    GolemCharacterSprite=1015

};
enum U7CharacterSprite randomCharacterSpriteID(void);
enum U7CharacterSprite randomHumanSpriteID(void);
int speedForCharacterSprite(enum U7CharacterSprite theType);
